const CarrierAdapter = require('./carriers/CarrierAdapter');
const crypto = require('crypto');

/**
 * Evri carrier adapter.
 * Uses mock responses in development; swap to real Evri API when business account is approved.
 *
 * Real Evri API endpoints (for when credentials are available):
 *   - POST https://api.evri.com/carriers/v1/parcels — create parcel / generate label
 *   - GET  https://api.evri.com/carriers/v1/parcels/{id}/tracking — tracking status
 *   - GET  https://api.evri.com/carriers/v1/parcelshops?postcode={pc} — drop-off locations
 */
class EvriAdapter extends CarrierAdapter {
  get carrierName() {
    return 'evri';
  }

  async generateLabel({ senderAddress, recipientAddress, weight, dimensions }) {
    if (this.config?.credentials?.apiKey) {
      return this._generateRealLabel({ senderAddress, recipientAddress, weight, dimensions });
    }
    return this._generateMockLabel({ senderAddress, recipientAddress });
  }

  async _generateRealLabel({ senderAddress, recipientAddress, weight, dimensions }) {
    // TODO: Implement real Evri API call when business account is approved
    // const response = await fetch('https://api.evri.com/carriers/v1/parcels', {
    //   method: 'POST',
    //   headers: {
    //     'Authorization': `Bearer ${this.config.credentials.apiKey}`,
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify({ sender: senderAddress, recipient: recipientAddress, weight, dimensions }),
    // });
    throw new Error('Real Evri API not yet implemented — awaiting business account approval');
  }

  async _generateMockLabel({ senderAddress, recipientAddress }) {
    const trackingCode = `EVR${crypto.randomBytes(6).toString('hex').toUpperCase()}`;

    return {
      trackingCode,
      labelUrl: null, // Will be generated as QR code
      qrCodeUrl: null, // Will be generated by LabelService
      cost: 3.49,
      carrier: 'evri',
      estimatedDelivery: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    };
  }

  async getTrackingStatus(trackingCode) {
    if (this.config?.credentials?.apiKey) {
      // TODO: Real API call
    }

    // Mock tracking statuses cycle
    const statuses = [
      { status: 'collected', location: 'ParcelShop - Customer Location' },
      { status: 'in_transit', location: 'Evri Hub - Birmingham' },
      { status: 'out_for_delivery', location: 'Local Courier' },
      { status: 'delivered', location: 'Merchant Warehouse' },
    ];

    const idx = Math.floor(Math.random() * statuses.length);
    return {
      status: statuses[idx].status,
      lastUpdate: new Date(),
      location: statuses[idx].location,
      estimatedDelivery: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    };
  }

  async getDropoffLocations({ postcode, limit = 5 }) {
    if (this.config?.credentials?.apiKey) {
      // TODO: Real API call to Evri ParcelShop finder
    }

    // Mock drop-off locations based on postcode
    const pc = (postcode || '').toUpperCase().replace(/\s/g, '');
    return [
      {
        id: `evri-${pc}-1`,
        name: 'Tesco Express',
        address: `45 High Street, ${postcode}`,
        lat: 51.5074,
        lng: -0.1278,
        distance: '0.2 miles',
        openingHours: '6am-11pm daily',
        type: 'ParcelShop',
      },
      {
        id: `evri-${pc}-2`,
        name: 'WHSmith',
        address: `12 Market Square, ${postcode}`,
        lat: 51.5080,
        lng: -0.1290,
        distance: '0.4 miles',
        openingHours: 'Mon-Sat 8am-6pm, Sun 10am-4pm',
        type: 'ParcelShop',
      },
      {
        id: `evri-${pc}-3`,
        name: 'Local Convenience Store',
        address: `78 Station Road, ${postcode}`,
        lat: 51.5065,
        lng: -0.1300,
        distance: '0.6 miles',
        openingHours: 'Mon-Sun 7am-10pm',
        type: 'ParcelShop',
      },
    ].slice(0, limit);
  }
}

module.exports = EvriAdapter;
